In [1]:
import torch

In [2]:
torch.__version__

'1.5.1'

In [3]:
torch.cuda.is_available()

True

In [4]:
torch.cuda.current_device()

0

In [5]:
torch.cuda.get_device_name(0)

'GeForce GTX 1650'

In [6]:
torch.cuda.memory_allocated()

0

In [7]:
import numpy as np

In [9]:
lst=[3,4,5,6]
arr=np.array(lst)

In [11]:
arr.dtype, arr.shape

(dtype('int32'), (4,))

##  numpy to tensor

In [12]:
tensors=torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [13]:
tensors[1:4]

tensor([4, 5, 6], dtype=torch.int32)

In [14]:
tensors[3]=100

In [15]:
tensors

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [16]:
arr# arr also changed when we chages tensors

array([  3,   4,   5, 100])

In [17]:
### Prevent this by using torch.tensor
tensor_arr=torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [20]:
tensor_arr[2]=90

In [21]:
tensor_arr

tensor([  3,   4,  90, 100], dtype=torch.int32)

In [22]:
arr

array([  3,   4,   5, 100])

In [23]:
# Matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [24]:
t3.shape

torch.Size([3, 2])

In [25]:
##zeros and ones
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [26]:
##zeros and ones
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [27]:
# araneg on tenosrs
a=torch.tensor(np.arange(0,15).reshape(5,3))

In [28]:
a

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)

In [30]:
a[2:4,:]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]], dtype=torch.int32)

## Tensor operations 

In [31]:
a= torch.tensor([1,2,3],dtype= torch.float)
b= torch.tensor([4,5,6],dtype= torch.float)
print(a+b)

tensor([5., 7., 9.])


In [33]:
torch.add(a,b)

tensor([5., 7., 9.])

In [35]:

c=torch.zeros(3)

In [36]:
torch.add(a,b,out=c) # here c is out tensor

tensor([5., 7., 9.])

In [37]:
c

tensor([5., 7., 9.])

In [38]:
torch.add(a,b).sum()

tensor(21.)

In [58]:
y = torch.rand([2,5])

In [59]:
y

tensor([[0.6174, 0.5560, 0.5743, 0.1653, 0.4089],
        [0.7147, 0.0596, 0.9216, 0.5652, 0.9977]])

In [60]:
y_new = y.view([1,10])#reshaing the array
y_new

tensor([[0.6174, 0.5560, 0.5743, 0.1653, 0.4089, 0.7147, 0.0596, 0.9216, 0.5652,
         0.9977]])

In [61]:
y_new.shape

torch.Size([1, 10])

## Dot Products and Mult Operations

In [40]:
x= torch.tensor([3,4,5], dtype=torch.float)
y = torch.tensor([4,5,6], dtype=torch.float)

In [41]:
x.mul(y)

tensor([12., 20., 30.])

In [42]:
x.dot(y)

tensor(62.)

In [43]:
x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]], dtype=torch.float)


In [44]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [45]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [46]:
x@y

tensor([[55., 53.],
        [90., 92.]])

##  Simple Backpropogation

In [49]:
x=torch.tensor(5.0,requires_grad=True)

In [50]:
x

tensor(5., requires_grad=True)

In [51]:
y = x**2
y

tensor(25., grad_fn=<PowBackward0>)

In [52]:
#### Back propogation y=2*x
y.backward()

In [53]:
print(x.grad)

tensor(10.)


In [54]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [55]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

we can automatically compute the derivative of y w.r.t. the tensors that have requires_grad set to True i.e. w and b. To compute the derivatives, we can call the .backward method on our result y

In [56]:
# Compute derivatives
y.backward()

derivates of y w.r.t the input tensors are stored in the .grad property of the respective tensors.



In [57]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)
