### Example : Simple model without class

#### 1) Design model (input, output, forward pass with different layers)
####  2) Construct loss and optimizer
#### 3) Training loop
#####     - Forward = compute prediction and loss
#####    - Backward = compute gradients
#####     - Update weights

In [1]:

import torch
import torch.nn as nn

# Linear regression
# f = w * x 

# here : f = 2 * x

# 0) Training samples
X = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
Y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)

# 1) Design Model: Weights to optimize and forward function
w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

print(X)
print(Y)
print(w)

tensor([1., 2., 3., 4.])
tensor([2., 4., 6., 8.])
tensor(0., requires_grad=True)


In [2]:
def forward(x):
    return w * x

print(f'Prediction before training: f(5) = {forward(5).item():.3f}')

Prediction before training: f(5) = 0.000


In [3]:
# 2) Define loss and optimizer
learning_rate = 0.01
n_iters = 100

# callable function
loss = nn.MSELoss()

optimizer = torch.optim.SGD([w], lr=learning_rate)
optimizer

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.01
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [4]:
# 3) Training loop
for epoch in range(n_iters):
    # predict = forward pass
    y_predicted = forward(X)

    # loss
    l = loss(Y, y_predicted)

    # calculate gradients = backward pass
    l.backward()

    # update weights
    optimizer.step()

    # zero the gradients after updating
    optimizer.zero_grad()

    if epoch % 10 == 0:
        print('epoch ', epoch+1, ': w = ', w, ' loss = ', l)

print(f'Prediction after training: f(5) = {forward(5).item():.3f}')

epoch  1 : w =  tensor(0.3000, requires_grad=True)  loss =  tensor(30., grad_fn=<MeanBackward0>)
epoch  11 : w =  tensor(1.6653, requires_grad=True)  loss =  tensor(1.1628, grad_fn=<MeanBackward0>)
epoch  21 : w =  tensor(1.9341, requires_grad=True)  loss =  tensor(0.0451, grad_fn=<MeanBackward0>)
epoch  31 : w =  tensor(1.9870, requires_grad=True)  loss =  tensor(0.0017, grad_fn=<MeanBackward0>)
epoch  41 : w =  tensor(1.9974, requires_grad=True)  loss =  tensor(6.7705e-05, grad_fn=<MeanBackward0>)
epoch  51 : w =  tensor(1.9995, requires_grad=True)  loss =  tensor(2.6244e-06, grad_fn=<MeanBackward0>)
epoch  61 : w =  tensor(1.9999, requires_grad=True)  loss =  tensor(1.0176e-07, grad_fn=<MeanBackward0>)
epoch  71 : w =  tensor(2.0000, requires_grad=True)  loss =  tensor(3.9742e-09, grad_fn=<MeanBackward0>)
epoch  81 : w =  tensor(2.0000, requires_grad=True)  loss =  tensor(1.4670e-10, grad_fn=<MeanBackward0>)
epoch  91 : w =  tensor(2.0000, requires_grad=True)  loss =  tensor(5.0768e

### Examples : With Class implementation

In [5]:
import torch
import torch.nn as nn

# Linear regression
# f = w * x 

# here : f = 2 * x

# 0) Training samples, watch the shape!
X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)
Y = torch.tensor([[2], [4], [6], [8]], dtype=torch.float32)
print(X)
print(Y)

tensor([[1.],
        [2.],
        [3.],
        [4.]])
tensor([[2.],
        [4.],
        [6.],
        [8.]])


In [6]:
n_samples, n_features = X.shape
print(f'#samples: {n_samples}, #features: {n_features}')

#samples: 4, #features: 1


In [7]:
# 0) create a test sample
X_test = torch.tensor([5], dtype=torch.float32)

In [8]:
# 1) Design Model, the model has to implement the forward pass!
# Here we can use a built-in model from PyTorch
input_size = n_features
output_size = n_features

In [9]:
# we can call this model with samples X
model = nn.Linear(input_size, output_size)
model

Linear(in_features=1, out_features=1, bias=True)

In [10]:
class LinearRegression(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegression, self).__init__()
        # define diferent layers
        self.lin = nn.Linear(input_dim, output_dim)
    def forward(self, x):
        return self.lin(x)

In [11]:
model = LinearRegression(input_size, output_size)
print(model)
#print(f'Prediction before training: f(5) = {model(X_test).item():.3f}')

LinearRegression(
  (lin): Linear(in_features=1, out_features=1, bias=True)
)


In [12]:
# 2) Define loss and optimizer
learning_rate = 0.01
n_iters = 150

loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [13]:
# 3) Training loop
for epoch in range(n_iters):
    # predict = forward pass with our model
    y_predicted = model(X)

    # loss
    l = loss(Y, y_predicted)

    # calculate gradients = backward pass
    l.backward()

    # update weights
    optimizer.step()

    # zero the gradients after updating
    optimizer.zero_grad()

    if epoch % 10 == 0:
        [w, b] = model.parameters() # unpack parameters
        print('epoch ', epoch+1, ': w = ', w[0][0].item(), ' loss = ', l)

print(f'Prediction after training: f(5) = {model(X_test).item():.3f}')

epoch  1 : w =  -0.48774492740631104  loss =  tensor(54.6175, grad_fn=<MeanBackward0>)
epoch  11 : w =  1.2137070894241333  loss =  tensor(1.7157, grad_fn=<MeanBackward0>)
epoch  21 : w =  1.4987900257110596  loss =  tensor(0.3294, grad_fn=<MeanBackward0>)
epoch  31 : w =  1.5557146072387695  loss =  tensor(0.2769, grad_fn=<MeanBackward0>)
epoch  41 : w =  1.5756131410598755  loss =  tensor(0.2599, grad_fn=<MeanBackward0>)
epoch  51 : w =  1.5892387628555298  loss =  tensor(0.2448, grad_fn=<MeanBackward0>)
epoch  61 : w =  1.6015475988388062  loss =  tensor(0.2305, grad_fn=<MeanBackward0>)
epoch  71 : w =  1.6133456230163574  loss =  tensor(0.2171, grad_fn=<MeanBackward0>)
epoch  81 : w =  1.6247714757919312  loss =  tensor(0.2045, grad_fn=<MeanBackward0>)
epoch  91 : w =  1.635856032371521  loss =  tensor(0.1926, grad_fn=<MeanBackward0>)
epoch  101 : w =  1.646612524986267  loss =  tensor(0.1814, grad_fn=<MeanBackward0>)
epoch  111 : w =  1.6570512056350708  loss =  tensor(0.1708, gra