In [1]:
import numpy as np
import torch

In [2]:
# Everything in pytorch is based on Tensor operations.
# A tensor can have different dimensions
# so it can be 1d, 2d, or even 3d and higher
# scalar, vector, matrix, tensor

# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(x)

tensor([0.])


In [3]:
x = torch.empty(3) # vector, 1D
print(x)

tensor([1.4013e-45, 0.0000e+00, 1.4013e-45])


In [4]:
x = torch.empty(2,3) # matrix, 2D
print(x)

tensor([[0.0000e+00, 1.4764e-41, 2.1177e-07],
        [6.6388e-07, 5.2666e-08, 3.3062e-09]])


In [5]:
x = torch.empty(2,2,3) # tensor, 3 dimensions
#x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [6]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([[0.9957, 0.6550, 0.8203],
        [0.5449, 0.1237, 0.6231],
        [0.3737, 0.2006, 0.9310],
        [0.4327, 0.3266, 0.3528],
        [0.0905, 0.0252, 0.3539]])


In [7]:
# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [8]:
# check size
print(x.size())

torch.Size([5, 3])


In [9]:
# check data type
print(x.dtype)

torch.float32


In [10]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

# check type
print(x.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


In [11]:
# construct from data
x = torch.tensor([5.5, 3])
print(x.size())

torch.Size([2])


In [13]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


In [15]:
# Operations
y = torch.rand(2, 2)
x = torch.rand(2, 2)

# elementwise addition
z = x + y
# torch.add(x,y)
print(z)

tensor([[1.1863, 0.8152],
        [1.2811, 0.2978]])


In [16]:
# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
# y.add_(x)

In [17]:
# substraction
z = x - y
z = torch.sub(x, y)
print(z)

tensor([[ 0.5175, -0.7941],
        [ 0.2201, -0.0582]])


In [18]:
# multiplication
z = x * y
z = torch.mul(x,y)
print(z)

tensor([[0.2849, 0.0085],
        [0.3982, 0.0213]])


In [19]:
# division
z = x / y
z = torch.div(x,y)
print(z)

tensor([[2.5477, 0.0131],
        [1.4149, 0.6732]])


In [20]:
# Slicing
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tensor([[0.5449, 0.7933, 0.3788],
        [0.9950, 0.4846, 0.6842],
        [0.4276, 0.4579, 0.2999],
        [0.2293, 0.0847, 0.5920],
        [0.9070, 0.7456, 0.8201]])
tensor([0.5449, 0.9950, 0.4276, 0.2293, 0.9070])
tensor([0.9950, 0.4846, 0.6842])
tensor(0.4846)


In [21]:
# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

0.48462051153182983


In [22]:
# Reshape with torch.view()
x = torch.randn(4, 4)
print(x)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

tensor([[-0.5423, -0.9182, -2.2332,  0.0440],
        [ 1.2672,  0.5655, -0.9280,  0.8233],
        [-0.5519, -0.0703,  0.1002,  0.4875],
        [-0.5788,  0.4766,  0.7044, -0.0666]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [23]:
# Numpy
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [24]:
# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [25]:
# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)


tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [26]:
# numpy to torch with .from_numpy(x)
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [27]:
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [29]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()
    print(z)

tensor([[ 0.4577,  0.0818, -1.2332,  1.0440],
        [ 2.2672,  1.5655,  0.0720,  1.8233],
        [ 0.4481,  0.9297,  1.1002,  1.4875],
        [ 0.4212,  1.4766,  1.7044,  0.9334]], device='cuda:0')
